FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# restapispring

Spring Boot rest api using mongodb.


**Dependencies**  
`Framework:` **Java Spring Framework**

`Database` **Mongodb**

## Pets Collection [/pet]

### PETS [GET]

+ Response 200 (application/json)

        {
            _id:5cbe004c1c9d440000a96db3
            name:"Spot"
            species:"dog"
            breed:"pitbull"
            
            _id:5cbe04ba1c9d440000a96db4
            name:"Daisy"
            species:"cat"
            breed:"calico"
            
            _id:5cbe055a1c9d440000a96db5
            name:"Bella"
            species:"dog"
            breed:"australian shepard"
        }